name: CI Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: composer:2
    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make lint
      - run: make test
